name: CI

on:
  push:
    branches:
      - develop
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose make

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Docker images and start services
        run: make init

      - name: Wait for MinIO
        run: |
          for i in {1..60}; do
            docker exec pasaeventos_api nc -z 172.16.0.9 9000 && echo "MinIO is up!" && break
            echo "Waiting for MinIO to start..."
            sleep 2
          done

      - name: Wait for API to be ready
        run: |
          for i in {1..90}; do
            nc -z localhost 8080 && echo "API is up!" && break
            echo "Waiting for API to start..."
            sleep 2
          done

      - name: Run tests inside API container
        run: make test
